    <!-- repository -->
    <table class="project_list">
      <tr>
        <th>Project</th>
        <th><a class="header" href="?o=descr">Description</a></th>
        <th><a class="header" href="?o=owner">Owner</a></th>
        <th><a class="header" href="?o=age">Last Change</a></th>
        <th></th>
      </tr>
<?php foreach($projects as $project) { ?>
      <tr class="dark">
      <td><a class="list" href="<?php echo '/'.$this->url('p='.$project['name']) ?>"><?php echo "${project['name']}" ?></a></td>
      <td><a class="list" title="<?php echo $project['description'] ?>" href="<?php echo "/${project['name']}" ?>"><?php echo $project['description'] ?></a></td>
        <td><i>felix</i></td>
        <td class="age2">5 days ago</td>
        <td class="link"><a href="/archlinux.git">summary</a> | <a href="/archlinux.git/shortlog">shortlog</a> | <a href="/archlinux.git/log">log</a> | <a href="/archlinux.git/tree">tree</a></td>
      </tr>
<?php } ?>
    </table>
