    <!-- repository -->
    <table class="project_list">
      <tr>
        <th>Project</th>
        <th><a class="header" href="?o=descr">Description</a></th>
        <th><a class="header" href="?o=owner">Owner</a></th>
        <th><a class="header" href="?o=age">Last Change</a></th>
        <th></th>
      </tr>
<?php foreach($projects as $proj) { ?>
      <tr class="dark">
      <td><a class="list" href="<?php echo '/'.$this->link("p={$proj['name']};a=summary") ?>"><?php echo $proj['name'] ?></a></td>
      <td><a class="list" title="<?php echo $proj['description'] ?>" href="<?php echo '/'.$this->link("p={$proj['name']};a=summary") ?>"><?php echo $proj['description'] ?></a></td>
        <td><em><?php echo $proj['head']->author->name ?></em></td>
        <td class="age2"><?php echo $this->date($proj['head']->committer->time) ?></td>
        <td class="link"><a href="<?php echo '/'.$this->link("p={$proj['name']};a=summary") ?>">summary</a> | <a href="<?php echo '/'.$this->link("p={$proj['name']};a=shortlog") ?>">shortlog</a> | <a href="<?php echo '/'.$this->link("p={$proj['name']};a=log") ?>">log</a> | <a href="<?php echo '/'.$this->link("p={$proj['name']};a=tree") ?>">tree</a></td>
      </tr>
<?php } ?>
    </table>
    <div class="page_footer">
      <a class="rss_logo" href="?a=opml">OPML</a>
      <a class="rss_logo" href="?a=project_index">TXT</a>
    </div>
