summary.phtml

    <table class="project_list">
      <tr>
        <th>Project</th>
        <th><a class="header" href="?o=descr">Description</a></th>
        <th><a class="header" href="?o=owner">Owner</a></th>
        <th><a class="header" href="?o=age">Last Change</a></th>
        <th></th>
      </tr>
      <tr class="dark">
        <td><a class="list" href="/archlinux.git">archlinux.git</a></td>
        <td><a class="list" title="My Arch Linux packages" href="/archlinux.git">My Arch Linux packages</a></td>
        <td><i>felix</i></td>
        <td class="age2">5 days ago</td>
        <td class="link"><a href="/archlinux.git">summary</a> | <a href="/archlinux.git/shortlog">shortlog</a> | <a href="/archlinux.git/log">log</a> | <a href="/archlinux.git/tree">tree</a></td>
      </tr>
      <tr class="light">
        <td><a class="list" href="/awesome-configs.git">awesome-configs.git</a></td>
        <td><a class="list" title="Configuration files for the Awesome window manager" href="/awesome-configs.git">Configuration files for the Awesome window manager</a></td>
        <td><i>felix</i></td>
        <td class="age1">23 hours ago</td>
        <td class="link"><a href="/awesome-configs.git">summary</a> | <a href="/awesome-configs.git/shortlog">shortlog</a> | <a href="/awesome-configs.git/log">log</a> | <a href="/awesome-configs.git/tree">tree</a></td>
      </tr>
      <tr class="dark">
        <td><a class="list" href="/galoader.git">galoader.git</a></td>
        <td><a class="list" title="Google Analytics loader" href="/galoader.git">Google Analytics loader</a></td>
        <td><i>felix</i></td>
        <td class="age2">3 months ago</td>
        <td class="link"><a href="/galoader.git">summary</a> | <a href="/galoader.git/shortlog">shortlog</a> | <a href="/galoader.git/log">log</a> | <a href="/galoader.git/tree">tree</a></td>
      </tr>
      <tr class="light">
        <td><a class="list" href="/lahu_keyboard.git">lahu_keyboard.git</a></td>
        <td><a class="list" title="Lahu keyboard layouts for Linux &amp; Windows" href="/lahu_keyboard.git">Lahu keyboard layouts for Linux &amp; Windows</a></td>
        <td><i>felix</i></td>
        <td class="age2">4 months ago</td>
        <td class="link"><a href="/lahu_keyboard.git">summary</a> | <a href="/lahu_keyboard.git/shortlog">shortlog</a> | <a href="/lahu_keyboard.git/log">log</a> | <a href="/lahu_keyboard.git/tree">tree</a></td>
      </tr>
      <tr class="dark">
        <td><a class="list" href="/learning_lahu.git">learning_lahu.git</a></td>
        <td><a class="list" title="My attempt at Lahu 101" href="/learning_lahu.git">My attempt at Lahu 101</a></td>
        <td><i>felix</i></td>
        <td class="age2">8 months ago</td>
        <td class="link"><a href="/learning_lahu.git">summary</a> | <a href="/learning_lahu.git/shortlog">shortlog</a> | <a href="/learning_lahu.git/log">log</a> | <a href="/learning_lahu.git/tree">tree</a></td>
      </tr>
      <tr class="light">
        <td><a class="list" href="/maildir2gmail.git">maildir2gmail.git</a></td>
        <td><a class="list" title="Maildir to GMail converter" href="/maildir2gmail.git">Maildir to GMail converter</a></td>
        <td><i>felix</i></td>
        <td class="age2">4 months ago</td>
        <td class="link"><a href="/maildir2gmail.git">summary</a> | <a href="/maildir2gmail.git/shortlog">shortlog</a> | <a href="/maildir2gmail.git/log">log</a> | <a href="/maildir2gmail.git/tree">tree</a></td>
      </tr>
      <tr class="dark">
        <td><a class="list" href="/okra.git">okra.git</a></td>
        <td><a class="list" title="Website analysis tool with plugins" href="/okra.git">Website analysis tool with plugins</a></td>
        <td><i>felix</i></td>
        <td class="age2">2 months ago</td>
        <td class="link"><a href="/okra.git">summary</a> | <a href="/okra.git/shortlog">shortlog</a> | <a href="/okra.git/log">log</a> | <a href="/okra.git/tree">tree</a></td>
      </tr>
      <tr class="light">
        <td><a class="list" href="/templates.git">templates.git</a></td>
        <td><a class="list" title="Various templates to start with" href="/templates.git">Various templates to start with</a></td>
        <td><i>felix</i></td>
        <td class="age2">11 days ago</td>
        <td class="link"><a href="/templates.git">summary</a> | <a href="/templates.git/shortlog">shortlog</a> | <a href="/templates.git/log">log</a> | <a href="/templates.git/tree">tree</a></td>
      </tr>
      <tr class="dark">
        <td><a class="list" href="/tinydns-dynamic.git">tinydns-dynamic.git</a></td>
        <td><a class="list" title="Dynamic DNS server and client for djbdns DNS server" href="/tinydns-dynamic.git">Dynamic DNS server and client for djbdns DNS server</a></td>
        <td><i>felix</i></td>
        <td class="age2">11 months ago</td>
        <td class="link"><a href="/tinydns-dynamic.git">summary</a> | <a href="/tinydns-dynamic.git/shortlog">shortlog</a> | <a href="/tinydns-dynamic.git/log">log</a> | <a href="/tinydns-dynamic.git/tree">tree</a></td>
      </tr>
    </table>
