    <!-- summary.phtml -->
    <div class="title">&nbsp;</div>
    <table class="projects_list">
      <tr id="metadata_desc"><td>description</td><td><?php echo $project['description'] ?></td></tr>
      <tr id="metadata_owner"><td>owner</td><td><?php echo $project['head']->author->name ?></td></tr>
      <tr id="metadata_lchange"><td>last change</td><td><?php echo strftime("%a, %d %b %Y %H:%M:%S %z",$project['head']->committer->time) ?></td></tr>
      <tr class="metadata_url"><td>URL</td><td><?php echo $config['git_url'].$project['name'] ?></td></tr>
    </table>
    <div class="header">
      <a class="title" href="?p=archlinux.git;a=shortlog">shortlog</a>
    </div>
    <?php echo $this->includeTemplate('shortlogtable') ?>
    <div class="header">
      <a class="title" href="?p=archlinux.git;a=heads">heads</a>
    </div>
    <table class="heads">
      <tr class="<?php ($cycle == 'dark') ? $cycle='light' : $cycle='dark'; echo $cycle ?>">
        <td><i>6 days ago</i></td>
        <td class="current_head"><a class="list name" href="?p=archlinux.git;a=shortlog;h=refs/heads/master">master</a></td>
        <td class="link"><a href="?p=archlinux.git;a=shortlog;h=refs/heads/master">shortlog</a> | <a href="?p=archlinux.git;a=log;h=refs/heads/master">log</a> | <a href="?p=archlinux.git;a=tree;h=refs/heads/master;hb=master">tree</a></td>
      </tr>
    </table>
    <div class="page_footer">
<?php if(isset($project['description'])){ ?>
      <div class="page_footer_text"><?php echo $project['description'] ?></div>
<?php } ?>
      <a class="rss_logo" href="?a=opml">OPML</a>
      <a class="rss_logo" href="?a=project_index">TXT</a>
    </div>
